In [1]:
import sys
import numpy as np

Basic Numpy arrays

In [15]:
a = np.array([1,2,3,4,5,6,7,8,9,10], dtype='int8')
b = np.array([5,6,7,8])

print(sys.getsizeof(a))
type(a)
a.dtype

106


dtype('int8')

In [9]:
listA = [1,2,3,4,5,6,7,8,9,10]
listB = [5,6,7,8]
print(sys.getsizeof(listA))
type(listA)

144


list

1) Indexing and Slicing <br>
2) Dimensions and shapes <br>
3) Operations along axis <br>
4) Broadcasting and vectorized operations <br>
5) Filtering with boolean arrays <br>

In [14]:
a[[0,2,-1]]

array([ 1,  3, 10], dtype=uint32)

Dimensions and shapes

In [17]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype='int32')

In [18]:
mat.shape

(2, 3)

In [20]:
mat.ndim

2

In [21]:
mat.size

6

In [23]:
mat[1] = 103

In [24]:
mat

array([[  1,   2,   3],
       [103, 103, 103]], dtype=int32)

In [26]:
c = np.arange(5)
c

array([0, 1, 2, 3, 4])

In [28]:
sys.getsizeof(1.6772632)

24

In [30]:
np.dtype(np.uint8).itemsize

1

In [32]:
a = list(range(1000))

In [44]:
%time sum([x**2 for x in a])

CPU times: user 241 µs, sys: 63 µs, total: 304 µs
Wall time: 308 µs


332833500

In [45]:
b = np.arange(1000)

In [54]:
%time np.sum(b ** 2)

CPU times: user 84 µs, sys: 21 µs, total: 105 µs
Wall time: 87.3 µs


332833500