In [8]:
import tensorflow as tf

* A tensor is a generalization of vectors and matrices to potentially higher dimensions
* Internally, TF represents tensors as n-dim array of base datatypes
* tensors are fundamental aspects of TF
* Tensors are the main objects that are passed around and manipulated through the program
* Each tensor represents a partially defined computation that will eventually produce a value
* TF programs work by building a graph of Tensor objects that detail how the tensors are related
* Running different parts of graph allow results to be generated
* Each tensor has a data type and shape
* Data types include - int32, float32, string and others
* Shape - represents that dimension of the data

In [9]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [10]:
print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


* Rank/Degree of Tensor
* Rank/Degree gives us number of dimensions of the tensor
* Shape gives us how many items we have in each dimension
* Shape always gives [rows, cols]

In [15]:
rank1_tensor = tf.Variable([1, 2, 3], tf.int32)
rank2_tensor = tf.Variable([[1,2],[3,4]], tf.int32)

In [19]:
tf.rank(rank1_tensor)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

* Initializing a tensor with 0 or 1

In [20]:
tf.ones([3,3,3])

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [22]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

* Changing shape - use tf.reshape
tf.reshape(tensor, [new_shape]) <br>
* -1 tells the tensor to calculate the size of the dimension in that place
* Any shape is valid so long as the number of elements (size) is same as original tensor

In [39]:
tensor1 = tf.ones([3,3,4])
tensor2 = tf.reshape(tensor1, [3,2,6])
tensor3 = tf.reshape(tensor1, [4, -1])

In [40]:
print(tensor1.shape)
print(tensor2.shape)
print(tensor3.shape)

(3, 3, 4)
(3, 2, 6)
(4, 9)


* Types of tensors
1. Variable
2. Constant
3. Placeholder
4. SparseTensor
* With the exception of variable, the rest of the tensor types are immutable
* immutable - value does not change during execution

* Evaluate a tensor - get its value

In [43]:
tensor1.numpy()

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)